const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.destroy,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{DireçaoDash: 0},
	{vida: 0},
	{Plataforma: 0},
	{Cronômetro: 0},
	{Projétil: 0},
	{ninja: 0},
	{Sólido: 0},
	{chao: 0},
	{Teclado: 0},
	{FundoJogo: 0},
	{Sprite2: 0},
	{inimigo: 0},
	{DestruirForaDoLayout: 0},
	{bala: 0},
	{Botão: 0},
	{Texto: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Mouse: 0},
	{TelaInicialFundo: 0},
	{Mosaico: 0},
	{Porta: 0},
	{Purta: 0},
	{ChavePorta: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite4: 0},
	{BotãoDePróximo: 0},
	{pngtransparentlightframemirrordoorfurniturebuildingretrothumbnail: 0},
	{pngtransparentlightframemirrordoorfurniturebuildingretrothumbnail2: 0},
	{Frame: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{botaodesetaemestilopixelart_4751472687removebgpreview: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Texto4: 0},
	{Frame5: 0},
	{Sprite11: 0},
	{CanDash: 0},
	{Dash: 0},
	{Chave: 0}
];

self.InstanceType = {
	ninja: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	FundoJogo: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	TelaInicialFundo: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Porta: class extends self.ISpriteInstance {},
	Purta: class extends self.ISpriteInstance {},
	ChavePorta: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BotãoDePróximo: class extends self.ISpriteInstance {},
	pngtransparentlightframemirrordoorfurniturebuildingretrothumbnail: class extends self.ISpriteInstance {},
	pngtransparentlightframemirrordoorfurniturebuildingretrothumbnail2: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	botaodesetaemestilopixelart_4751472687removebgpreview: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Frame5: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {}
}